#ENC[AES256_GCM,data:2AezgGBHMPgh9XpTbSaRj2o5QK8QzpZmC0pZPqoB4R9NKhE2/iMuF9zO2qaAF4Z0M13+kXeGYIXdfYAVMH+izFvT099u,iv:84TKmGtQNin1vqURjH97l/rDHKcsVXh0Id3YtLSA0fM=,tag:JVmfMpfiar+xf1WL3ECndA==,type:comment]
#ENC[AES256_GCM,data:B6/esHeRrDZXn6zKqtiin2pwNG2M3fDX7zWiVEQ56tqb/LyEMEXFuOw10KpH+Lmq4dmQxqd886d+x8+8BAN0VTJoNE7uFMsv,iv:krObpRzZjuHWV2/axKbzc99pRmiHPiZINGMGjXOQATA=,tag:y2lNsOqEWX1HWW1MlNSL9A==,type:comment]
#ENC[AES256_GCM,data:JXPCtWBWLUmR846eTsspwxgZ3vuAEMN013bFYK+nVgJXBMEALuhl/fHwoUhrbSspg9R5XFMJ37+CsroBvJgmeNMp9AmeQ2jP,iv:a+BoMBCWFn+mZkuCoGUKRyQKj7IK6bBhUJSwvnG14Wo=,tag:0oeCP/Xz59tpMgL4bPSJVA==,type:comment]
placeholder_note: ENC[AES256_GCM,data:qXS9pDGPihcY6ES3Vbi9hrdonP+4imPx1b45uw40avgUjr1HS3ljAG7KmFsfvva5cpMHRJAvwbuJKn4=,iv:4ymEq/Xqdt1m4jgVuZkW+MY7+x1VBSLVkvmlYlaYNIM=,tag:uK2nwWatEIwwDGIFfQHUZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUTM5LzJNS3ZERFRFU1Ez
            dlJ5RzBoRVVTU2NOOWpCWDg5RXBqd1REa1U4Cm9rSllFTDAvUEZuUW5BZlhYRFVV
            VzNieHhpdmV6OXFUbCs1QlQvV0Nod28KLS0tIFozWElOZmY1S3VpT0c1TTRGSTlO
            d2xnZy8rejZ3ZXpaOGgvTHJDajQ0aVUKGN2agCm3jI7oTJKBDS+35Pb5zaY2lkNe
            qMuajQTQ0gVbbEjIkhIjxWArKW3uddSVUvm6CPWkX47zyL78Bh0hKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cp55xs9efll05fv2wcjmhxqhzlssnvgy8garz7lr9q7ue0ht6ags9knfx0
    lastmodified: "2026-08-13T17:00:13Z"
    mac: ENC[AES256_GCM,data:xhNVc1fTLmlKo8Zp4gaWaUx+0fn127LTkBPr+GxOdtNcQQAH9rJkc3nwoQTdXep/RryigQ+mbqzAoe0zljbpiLdc+8AvkBg/9y6DS2m797f5aZg2Z+U6OadUpJwRk95o92e/53Lj/C7WXGg4PMmiqprV8zSCXCLlWA+fcbkJDWs=,iv:gsRa2LCjeJ5DrC2j1w0q1aKkpjcUlZpFYvc0rBJgpvk=,tag:awcLAgSexIEQuWzME9DFVA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
