#ENC[AES256_GCM,data:5bqNtPLB02J3ON30AWUOpZY2myGgfWhVoEHVjzrC/MwkIrRYcDXdh/1qatzlxSQs/T+Hx3NJwQcw+pPK6wO/R9C48roU,iv:nAs0iH78Am3rPOdaDXx41ZZAhzHkLF4zy85BnH91lvI=,tag:VN2g84jCgqU9eQvjCca0ig==,type:comment]
#ENC[AES256_GCM,data:BpAMIouS1GfNKlzOqfCQS/hfWeHfyX11wC9uxqm6W0gGEZAjarX9Y0Y8MXhsACauIlBNHNeJNl2S4YuRfjhKSdUVE9amY6bH,iv:S85/O+YS7k1d5/hIc+DcXWLoTk1uLnqBexC+0hPPTns=,tag:7nQ8J5ktM65KsWHFHGySyg==,type:comment]
#ENC[AES256_GCM,data:8JMRUv/FQCC6fOjX/UY684ccft3uxbvXNrxuGP00idjMmf0Nmb6BnXyPz3XLJwJqpAq2Y686jrz5rlK2oCcWxnBaZi3EVAVR,iv:N5Gm/6tQ1VernTOLg5+Aiw9zyex/9Vtok31Kd+l+GfY=,tag:3hzaEQ7ZVPySoJx6mwTjNg==,type:comment]
placeholder_note: ENC[AES256_GCM,data:eXpWgA5ylFJpVj6hYgnePrd2d3TEN9o8NR1r3K0vDX600qIFL5g9ymsCT+WBUdtjFnJL62wqVxMDWSE=,iv:uUQULhh3o3eiSDkY8d9EjnrcvNy0l52I8bsEn4Ga2Xk=,tag:FGiwFKaPiIm3oMuyaDao8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSWpPTmp0a3lFcHBsbUhv
            TVZIREh0TXFXV1JyUUpZaGhyY0RxcCt1dmtFClVvbUlycEU2eHRhcnIxK3FCOVJh
            c1hSalNRc2tNYmxHMjlyeTBhUUpZbVkKLS0tIGFuTHd1SS9CVEM1VERvbGVoOElK
            NFgycXVXUUdEcTFJUzhsd0RLYWx3ekUKesF1ZLcpD6TKoEMrcjtl8xNI7vMcdlZi
            Byy3QV1Wvn+tyGtqv3iMmOKY+8xHA8gKhHVR4hWZnfCMvpBus5zOsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngslnaavftjgan67etu0jpekqyntp22a9t59p3vytqmfek8f737sw4eghu
    lastmodified: "2026-08-14T02:13:06Z"
    mac: ENC[AES256_GCM,data:yZXCDTTTZlW4yTkCiHyVYxtNdwdBs3Y28zghM8tRhSvz7cLzoRNm1X1xd9Z2SGIxC4hwDLb+YAHfzbThUfDG+dBJXxHTToJ+ENPYmwA/w3c4qbkkoVZosTHkQy8+NFcZtn9BkloFt6ZLsewBnRqVqften/J2+J+gHjxVfpWsYVs=,iv:h/QiOIKarGKJQJ3hl0WOErZRD+/kBfeCk7BKHaCg2FE=,tag:oD5o3dTO/PxwGJCbaRw8nQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
