"""CreateWorkspace use case (FR-ID-2). Creating a workspace and making its
creator the sole Owner are one atomic operation — a workspace with zero
Owners should never be observable, not even transiently.

``workspace_id`` is pre-generated by the caller (http/deps.py's
get_new_workspace_connection), not by this use case: memberships' RLS
WITH CHECK needs ``app.tenant_id`` set to the new workspace's id
*before* the owner membership INSERT runs, and only the dependency layer
that opened the connection can do that — by the time this use case's
``execute()`` runs, tenant context is already correctly set to the id
it's about to receive back in the command.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from uuid import UUID

from aether.domain.entities import MembershipRole, Workspace
from aether.ports.audit import AuditLogPort
from aether.ports.repositories import MembershipRepositoryPort, WorkspaceRepositoryPort
from aether.ports.security import IdPort


@dataclass(frozen=True, slots=True)
class CreateWorkspaceCommand:
    workspace_id: UUID
    name: str
    owner_user_id: UUID


class CreateWorkspace:
    def __init__(
        self,
        *,
        workspaces: WorkspaceRepositoryPort,
        memberships: MembershipRepositoryPort,
        audit_log: AuditLogPort,
        ids: IdPort,
    ) -> None:
        self._workspaces = workspaces
        self._memberships = memberships
        self._audit_log = audit_log
        self._ids = ids

    async def execute(self, command: CreateWorkspaceCommand) -> Workspace:
        workspace_id = command.workspace_id
        # The *last* 8 hex chars, not the first: workspace_id is a
        # UUIDv7 (ADR-4.3), whose first 48 bits are a millisecond
        # timestamp — the first 8 hex chars are therefore nearly
        # constant across any ~65-second window (2**32 ms), so two
        # same-named workspaces created close together would collide on
        # slug. The last 8 hex chars fall entirely within UUIDv7's
        # random tail, which is what a uniqueness suffix actually needs.
        slug = f"{_slugify(command.name)}-{workspace_id.hex[-8:]}"

        workspace = await self._workspaces.create(
            id=workspace_id, name=command.name, slug=slug, settings={}, model_policy={}
        )
        await self._memberships.create(
            id=self._ids.new_id(),
            workspace_id=workspace_id,
            user_id=command.owner_user_id,
            role=MembershipRole.OWNER,
        )
        await self._audit_log.record(
            id=self._ids.new_id(),
            workspace_id=workspace_id,
            actor_user_id=command.owner_user_id,
            actor_key_id=None,
            action="workspace.created",
            target_type="workspace",
            target_id=workspace_id,
            metadata={},
        )
        return workspace


def _slugify(name: str) -> str:
    lowered = name.strip().lower()
    slug = re.sub(r"[^a-z0-9]+", "-", lowered).strip("-")
    return slug or "workspace"
